'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace hostBasculaPL
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Basculas", [Namespace]:="http://schemas.datacontract.org/2004/07/gplServiceWcfLibrary")>  _
    Public Enum Basculas As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Bascula1 = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Bascula2 = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoBascula", [Namespace]:="http://schemas.datacontract.org/2004/07/gplServiceWcfLibrary"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoBascula
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CadenaOriginalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CargaField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CargaFinalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodEstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoDescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MatriculaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PMAField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PesoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SiloField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CadenaOriginal() As String
            Get
                Return Me.CadenaOriginalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CadenaOriginalField, value) <> true) Then
                    Me.CadenaOriginalField = value
                    Me.RaisePropertyChanged("CadenaOriginal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Carga() As Double
            Get
                Return Me.CargaField
            End Get
            Set
                If (Me.CargaField.Equals(value) <> true) Then
                    Me.CargaField = value
                    Me.RaisePropertyChanged("Carga")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CargaFinal() As Double
            Get
                Return Me.CargaFinalField
            End Get
            Set
                If (Me.CargaFinalField.Equals(value) <> true) Then
                    Me.CargaFinalField = value
                    Me.RaisePropertyChanged("CargaFinal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEstado() As String
            Get
                Return Me.CodEstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodEstadoField, value) <> true) Then
                    Me.CodEstadoField = value
                    Me.RaisePropertyChanged("CodEstado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoDescripcion() As String
            Get
                Return Me.EstadoDescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoDescripcionField, value) <> true) Then
                    Me.EstadoDescripcionField = value
                    Me.RaisePropertyChanged("EstadoDescripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Matricula() As String
            Get
                Return Me.MatriculaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatriculaField, value) <> true) Then
                    Me.MatriculaField = value
                    Me.RaisePropertyChanged("Matricula")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Operario() As String
            Get
                Return Me.OperarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperarioField, value) <> true) Then
                    Me.OperarioField = value
                    Me.RaisePropertyChanged("Operario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PMA() As Double
            Get
                Return Me.PMAField
            End Get
            Set
                If (Me.PMAField.Equals(value) <> true) Then
                    Me.PMAField = value
                    Me.RaisePropertyChanged("PMA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Peso() As Double
            Get
                Return Me.PesoField
            End Get
            Set
                If (Me.PesoField.Equals(value) <> true) Then
                    Me.PesoField = value
                    Me.RaisePropertyChanged("Peso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Silo() As String
            Get
                Return Me.SiloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SiloField, value) <> true) Then
                    Me.SiloField = value
                    Me.RaisePropertyChanged("Silo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EstadoComando", [Namespace]:="http://schemas.datacontract.org/2004/07/gplServiceWcfLibrary"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EstadoComando
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CadenaOriginalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetalleErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExiteErrorField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CadenaOriginal() As String
            Get
                Return Me.CadenaOriginalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CadenaOriginalField, value) <> true) Then
                    Me.CadenaOriginalField = value
                    Me.RaisePropertyChanged("CadenaOriginal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodError() As String
            Get
                Return Me.CodErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodErrorField, value) <> true) Then
                    Me.CodErrorField = value
                    Me.RaisePropertyChanged("CodError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetalleError() As String
            Get
                Return Me.DetalleErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DetalleErrorField, value) <> true) Then
                    Me.DetalleErrorField = value
                    Me.RaisePropertyChanged("DetalleError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExiteError() As Boolean
            Get
                Return Me.ExiteErrorField
            End Get
            Set
                If (Me.ExiteErrorField.Equals(value) <> true) Then
                    Me.ExiteErrorField = value
                    Me.RaisePropertyChanged("ExiteError")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="hostBasculaPL.IhostBascula")>  _
    Public Interface IhostBascula
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/DameEstado", ReplyAction:="http://tempuri.org/IhostBascula/DameEstadoResponse")>  _
        Function DameEstado(ByVal idBascula As hostBasculaPL.Basculas) As hostBasculaPL.EstadoBascula
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/DameEstado", ReplyAction:="http://tempuri.org/IhostBascula/DameEstadoResponse")>  _
        Function DameEstadoAsync(ByVal idBascula As hostBasculaPL.Basculas) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoBascula)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/CargaDatos", ReplyAction:="http://tempuri.org/IhostBascula/CargaDatosResponse")>  _
        Function CargaDatos(ByVal numBascula As hostBasculaPL.Basculas, ByVal _codOperario As String, ByVal _matricula As String, ByVal _pma As Double, ByVal _carga As Double, ByVal _silo As String) As hostBasculaPL.EstadoComando
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/CargaDatos", ReplyAction:="http://tempuri.org/IhostBascula/CargaDatosResponse")>  _
        Function CargaDatosAsync(ByVal numBascula As hostBasculaPL.Basculas, ByVal _codOperario As String, ByVal _matricula As String, ByVal _pma As Double, ByVal _carga As Double, ByVal _silo As String) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoComando)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/FinCarga", ReplyAction:="http://tempuri.org/IhostBascula/FinCargaResponse")>  _
        Function FinCarga(ByVal idBascula As hostBasculaPL.Basculas) As hostBasculaPL.EstadoComando
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IhostBascula/FinCarga", ReplyAction:="http://tempuri.org/IhostBascula/FinCargaResponse")>  _
        Function FinCargaAsync(ByVal idBascula As hostBasculaPL.Basculas) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoComando)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IhostBasculaChannel
        Inherits hostBasculaPL.IhostBascula, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IhostBasculaClient
        Inherits System.ServiceModel.ClientBase(Of hostBasculaPL.IhostBascula)
        Implements hostBasculaPL.IhostBascula
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DameEstado(ByVal idBascula As hostBasculaPL.Basculas) As hostBasculaPL.EstadoBascula Implements hostBasculaPL.IhostBascula.DameEstado
            Return MyBase.Channel.DameEstado(idBascula)
        End Function
        
        Public Function DameEstadoAsync(ByVal idBascula As hostBasculaPL.Basculas) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoBascula) Implements hostBasculaPL.IhostBascula.DameEstadoAsync
            Return MyBase.Channel.DameEstadoAsync(idBascula)
        End Function
        
        Public Function CargaDatos(ByVal numBascula As hostBasculaPL.Basculas, ByVal _codOperario As String, ByVal _matricula As String, ByVal _pma As Double, ByVal _carga As Double, ByVal _silo As String) As hostBasculaPL.EstadoComando Implements hostBasculaPL.IhostBascula.CargaDatos
            Return MyBase.Channel.CargaDatos(numBascula, _codOperario, _matricula, _pma, _carga, _silo)
        End Function
        
        Public Function CargaDatosAsync(ByVal numBascula As hostBasculaPL.Basculas, ByVal _codOperario As String, ByVal _matricula As String, ByVal _pma As Double, ByVal _carga As Double, ByVal _silo As String) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoComando) Implements hostBasculaPL.IhostBascula.CargaDatosAsync
            Return MyBase.Channel.CargaDatosAsync(numBascula, _codOperario, _matricula, _pma, _carga, _silo)
        End Function
        
        Public Function FinCarga(ByVal idBascula As hostBasculaPL.Basculas) As hostBasculaPL.EstadoComando Implements hostBasculaPL.IhostBascula.FinCarga
            Return MyBase.Channel.FinCarga(idBascula)
        End Function
        
        Public Function FinCargaAsync(ByVal idBascula As hostBasculaPL.Basculas) As System.Threading.Tasks.Task(Of hostBasculaPL.EstadoComando) Implements hostBasculaPL.IhostBascula.FinCargaAsync
            Return MyBase.Channel.FinCargaAsync(idBascula)
        End Function
    End Class
End Namespace
